name: Build on EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Connect & Build on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app || mkdir ~/app && cd ~/app
            git pull https://github.com/AhmedAlhusaini/DEPI-DevOpsNinjas-Project-Showcase.git
            docker-compose build
            docker-compose up -d
